[pytest]
addopts =
    --nbmake
    --nbmake-timeout=600
    --ignore=xai-for-random-forest/Bio-5-HandsOn_AML_EDA.ipynb
    --ignore=xai-for-random-forest/Bio-6-HandsOn_AML_RandomForest.ipynb
    --ignore=xai-for-random-forest/Bio-7-HandsOn_AML_XAI.ipynb
    --ignore=xai-for-transformer/1-Tutorial_Transformer_Model.ipynb
    --ignore=xai-for-transformer/2-Tutorial_AttentionMaps_Text.ipynb
    --ignore=xai-for-transformer/3-Tutorial_VIT_Model.ipynb
    --ignore=xai-for-transformer/4-Tutorial_AttentionMaps_Images.ipynb

testpaths =
    xai-for-cnn
    xai-for-random-forest
    xai-for-transformer