[pytest]
addopts =
    --nbmake
    --nbmake-timeout=600
    --ignore=xai-for-random-forest/Bio-5-HandsOn_AML_EDA.ipynb
    --ignore=xai-for-random-forest/Bio-6-HandsOn_AML_RandomForest.ipynb
    --ignore=xai-for-random-forest/Bio-7-HandsOn_AML_XAI.ipynb

testpaths =
    xai-for-cnn
    xai-for-random-forest
    xai-for-transformers