name: test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  notebook-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tutorial:
          - name: cnn
            path: xai-for-cnn
            requirements: requirements_xai-for-cnn.txt

          - name: random-forest
            path: xai-for-random-forest
            requirements: requirements_xai-for-random-forest.txt

          - name: transformer
            path: xai-for-transformer
            requirements: requirements_xai-for-transformer.txt

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest nbmake
          pip install -r ${{ matrix.tutorial.requirements }}

      - name: Run notebook tests
        run: |
          pytest ${{ matrix.tutorial.path }}